export const ADD_ENTRIES = 'ADD_ENTRIES';
export const CLEAR_ENTRIES = 'CLEAR_ENTRIES';
export const DISMISS_ENTRY = 'DISMISS_ENTRY';
export const FETCH_ENTRIES_FAILED = 'FETCH_ENTRIES_FAILED';
export const SELECT_ENTRY = 'SELECT_ENTRY';
